name: mediscan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - poppler
  - tesseract
  - pip:
      - streamlit==1.32.2
      - openai==1.17.0
      - pdf2image==1.16.3
      - Pillow==10.2.0
      - pytesseract==0.3.10
      - python-dotenv==1.0.1
      - requests==2.31.0
      - pymupdf
